# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/defaults.ipynb (unless otherwise specified).

__all__ = ['score2class', 'class2score']

# Cell
score2class = {
    0: 0,
    0.25: 1,
    0.5: 2,
    0.75: 3,
    1: 4
}

class2score = {v: k for k, v in score2class.items()}