# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/metrics.ipynb (unless otherwise specified).

__all__ = ['PearsonCorrCoef']

# Cell
from scipy.stats import pearsonr

# Cell
class PearsonCorrCoef:

    def __init__(self):
        self._labels = []
        self._predictions = []

        self._pearson_corr_coef = 0

    def reset(self):
        self._labels = []
        self._predictions = []

    def update(self, predictions, labels):
        self._predictions.extend(predictions)
        self._labels.extend(labels)

        self._pearson_corr_coef = pearsonr(self._labels, self._predictions)[0]

    def get_metric(self):
        return self._pearson_corr_coef